export const products = [
    { id: 1, title: "Super Mario Bros.", provider: "Nintendo", year: 1985, image: "images/super_mario_bros.jpg", genre: "Platformer", price: 14.99, stock: 24 },
    { id: 2, title: "The Legend of Zelda", provider: "Nintendo", year: 1986, image: "images/legend_of_zelda.jpg", genre: "Action", price: 19.99, stock: 18 },
    { id: 3, title: "Sonic the Hedgehog", provider: "Sega", year: 1991, image: "images/sonic_the_hedgehog.jpg", genre: "Platformer", price: 12.50, stock: 30 },
    { id: 4, title: "Pac-Man", provider: "Namco", year: 1980, image: "images/pacman.jpg", genre: "Arcade", price: 9.99, stock: 40 },
    { id: 5, title: "Tetris (Game Boy)", provider: "Nintendo", year: 1989, image: "images/tetris_gb.jpg", genre: "Puzzle", price: 11.99, stock: 36 },
    { id: 6, title: "Street Fighter II", provider: "Capcom", year: 1991, image: "images/street_fighter_ii.jpg", genre: "Fighting", price: 24.99, stock: 12 },
    { id: 7, title: "Mortal Kombat II", provider: "Midway", year: 1993, image: "images/mortal_kombat_ii.jpg", genre: "Fighting", price: 22.00, stock: 10 },
    { id: 8, title: "Mega Man 2", provider: "Capcom", year: 1988, image: "images/mega_man_2.jpg", genre: "Action", price: 17.50, stock: 14 },
    { id: 9, title: "Castlevania", provider: "Konami", year: 1986, image: "images/castlevania.jpg", genre: "Action", price: 16.00, stock: 15 },
    { id: 10, title: "Metroid", provider: "Nintendo", year: 1986, image: "images/metroid.jpg", genre: "Action", price: 18.99, stock: 11 },
    { id: 11, title: "Donkey Kong", provider: "Nintendo", year: 1981, image: "images/donkey_kong.jpg", genre: "Arcade", price: 13.99, stock: 20 },
    { id: 12, title: "Final Fantasy VI", provider: "Square", year: 1994, image: "images/final_fantasy_vi.jpg", genre: "RPG", price: 29.99, stock: 8 },
    { id: 13, title: "Chrono Trigger", provider: "Square", year: 1995, image: "images/chrono_trigger.jpg", genre: "RPG", price: 34.99, stock: 6 },
    { id: 14, title: "Pokémon Red", provider: "Nintendo", year: 1996, image: "images/pokemon_red.jpg", genre: "RPG", price: 27.50, stock: 22 },
    { id: 15, title: "Dragon Quest III", provider: "Enix", year: 1988, image: "images/dragon_quest_iii.jpg", genre: "RPG", price: 21.00, stock: 9 },
    { id: 16, title: "Contra", provider: "Konami", year: 1987, image: "images/contra.jpg", genre: "Action", price: 15.00, stock: 16 },
    { id: 17, title: "Golden Axe", provider: "Sega", year: 1989, image: "images/golden_axe.jpg", genre: "BeatEmUp", price: 14.99, stock: 13 },
    { id: 18, title: "Ghosts 'n Goblins", provider: "Capcom", year: 1985, image: "images/ghosts_n_goblins.jpg", genre: "Platformer", price: 16.50, stock: 7 },
    { id: 19, title: "DOOM", provider: "id Software", year: 1993, image: "images/doom_1993.jpg", genre: "Shooter", price: 19.99, stock: 21 },
    { id: 20, title: "Wolfenstein 3D", provider: "id Software", year: 1992, image: "images/wolfenstein_3d.jpg", genre: "Shooter", price: 17.00, stock: 19 },
    { id: 21, title: "Duke Nukem 3D", provider: "3D Realms", year: 1996, image: "images/duke_nukem_3d.jpg", genre: "Shooter", price: 18.50, stock: 10 },
    { id: 22, title: "EarthBound", provider: "Nintendo", year: 1994, image: "images/earthbound.jpg", genre: "RPG", price: 39.99, stock: 5 },
    { id: 23, title: "Metal Gear", provider: "Konami", year: 1987, image: "images/metal_gear.jpg", genre: "Stealth", price: 20.00, stock: 12 },
    { id: 24, title: "Resident Evil", provider: "Capcom", year: 1996, image: "images/resident_evil.jpg", genre: "Horror", price: 26.99, stock: 9 },
    { id: 25, title: "Tomb Raider", provider: "Eidos", year: 1996, image: "images/tomb_raider.jpg", genre: "Action", price: 22.99, stock: 14 },
    { id: 26, title: "Fallout", provider: "Interplay", year: 1997, image: "images/fallout_1997.jpg", genre: "RPG", price: 24.99, stock: 8 },
    { id: 27, title: "Sonic the Hedgehog 2", provider: "Sega", year: 1992, image: "images/sonic_2.jpg", genre: "Platformer", price: 13.50, stock: 25 },
    { id: 28, title: "Sonic CD", provider: "Sega", year: 1993, image: "images/sonic_cd.jpg", genre: "Platformer", price: 14.00, stock: 11 },
    { id: 29, title: "NBA Jam", provider: "Midway", year: 1993, image: "images/nba_jam.jpg", genre: "Sports", price: 12.99, stock: 17 },
    { id: 30, title: "Gran Turismo", provider: "Polyphony Digital", year: 1997, image: "images/gran_turismo.jpg", genre: "Racing", price: 29.50, stock: 7 },
    { id: 31, title: "Paperboy", provider: "E.A.", year: 1985, image: "images/paperboy.jpg", genre: "Arcade", price: 9.50, stock: 26 },
    { id: 32, title: "Street of Rage 2", provider: "Sega", year: 1992, image: "images/street_of_rage_2.jpg", genre: "BeatEmUp", price: 15.99, stock: 12 },
    { id: 33, title: "The Secret of Mana", provider: "Square", year: 1993, image: "images/secret_of_mana.jpg", genre: "RPG", price: 28.00, stock: 6 },
    { id: 34, title: "Super Metroid", provider: "Nintendo", year: 1994, image: "images/super_metroid.jpg", genre: "Action", price: 34.00, stock: 4 },
    { id: 35, title: "Aladdin (Sega Genesis)", provider: "Virgin", year: 1993, image: "images/aladdin_genesis.jpg", genre: "Platformer", price: 12.00, stock: 15 },
    { id: 36, title: "Teenage Mutant Ninja Turtles (Arcade)", provider: "Konami", year: 1989, image: "images/tmnt_arcade.jpg", genre: "BeatEmUp", price: 14.50, stock: 13 },
    { id: 37, title: "Ridge Racer", provider: "Namco", year: 1993, image: "images/ridge_racer.jpg", genre: "Racing", price: 16.99, stock: 10 },
    { id: 38, title: "ace combat 2", provider: "Namco", year: 1997, image: "images/ace_combat_2.jpg", genre: "Simulation", price: 19.99, stock: 9 },
    { id: 39, title: "Bubble Bobble", provider: "Taito", year: 1986, image: "images/bubble_bobble.jpg", genre: "Arcade", price: 11.99, stock: 21 },
    { id: 40, title: "Punch-Out!! (NES)", provider: "Nintendo", year: 1987, image: "images/punch_out.jpg", genre: "Sports", price: 14.99, stock: 16 }
]